fdroidcl repo add CollaboraOffice https://www.collaboraoffice.com/downloads/fdroid/repo
fdroidcl repo add Cromium https://www.cromite.org/fdroid/repo
fdroidcl repo add GuardianProject https://guardianproject.info/fdroid/repo
fdroidcl repo add IzzyOnDroid https://apt.izzysoft.de/fdroid/repo
fdroidcl repo add JulianRepo https://julianfairfax.gitlab.io/fdroid-repo/fdroid/repo
fdroidcl repo add LibRetro https://fdroid.libretro.com/repo
fdroidcl repo add MicroG https://microg.org/fdroid/repo
fdroidcl repo add MollyFoss https://molly.im/fdroid/foss/repo
fdroidcl repo add Newpipe https://archive.newpipe.net/fdroid/repo
fdroidcl repo add Session https://fdroid.getsession.org/fdroid/repo